services:
  postres:
    container_name: postgres
    ports:
      - "5432:5432"
    build:
      context: ./
      dockerfile: infra/Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
